const NOTES_KEY="notiz-app-notes",THEME_KEY="notiz-app-theme";let notes=[],editingId=null;
const $=id=>document.getElementById(id);
const noteForm=$("noteForm"),title=$("noteTitle"),content=$("noteContent"),grid=$("notesGrid"),search=$("searchInput"),count=$("noteCount"),modal=$("editModal"),editForm=$("editForm"),editTitle=$("editTitle"),editContent=$("editContent");
function load(){try{notes=JSON.parse(localStorage.getItem(NOTES_KEY))||[]}catch{notes=[]}document.body.classList.toggle("dark",localStorage.getItem(THEME_KEY)==="dark");themeIcon()}
function save(){localStorage.setItem(NOTES_KEY,JSON.stringify(notes))}
function themeIcon(){$("themeToggle").textContent=document.body.classList.contains("dark")?"☀️":"🌙"}
function render(){const q=search.value.trim().toLowerCase(),list=notes.filter(n=>!q||n.title.toLowerCase().includes(q)||n.content.toLowerCase().includes(q));grid.replaceChildren();if(!list.length){const e=document.createElement("div");e.className="empty";e.innerHTML=notes.length?"<div class='empty-icon'>🔎</div><h2>Keine Notizen gefunden</h2><p>Versuche einen anderen Suchbegriff.</p>":"<div class='empty-icon'>📝</div><h2>Noch keine Notizen</h2><p>Erstelle deine erste Notiz.</p>";grid.append(e)}else list.forEach(n=>grid.append(card(n)));count.textContent=list.length+" "+(list.length===1?"Notiz":"Notizen")}
function card(n){const a=document.createElement("article");a.className="note-card";a.dataset.id=n.id;const h=document.createElement("h3");h.className="note-title";h.textContent=n.title;const p=document.createElement("p");p.className="note-content";p.textContent=n.content;const d=document.createElement("div");d.className="note-date";d.textContent="Erstellt: "+new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(n.createdAt));const actions=document.createElement("div");actions.className="note-actions";const edit=document.createElement("button");edit.textContent="Bearbeiten";edit.onclick=()=>openEdit(n.id);const del=document.createElement("button");del.className="delete";del.textContent="Löschen";del.onclick=()=>{if(confirm("Möchtest du diese Notiz wirklich löschen?")){a.classList.add("removing");setTimeout(()=>{notes=notes.filter(x=>x.id!==n.id);save();render()},220)}};actions.append(edit,del);a.append(h,p,d,actions);return a}
function openEdit(id){const n=notes.find(x=>x.id===id);if(!n)return;editingId=id;editTitle.value=n.title;editContent.value=n.content;modal.classList.add("open");editTitle.focus()}
function closeEdit(){editingId=null;modal.classList.remove("open");editForm.reset()}
noteForm.onsubmit=e=>{e.preventDefault();const t=title.value.trim(),c=content.value.trim();if(!t||!c)return;notes.unshift({id:crypto.randomUUID(),title:t,content:c,createdAt:new Date().toISOString()});save();render();noteForm.reset();title.focus()};
$("clearForm").onclick=()=>{noteForm.reset();title.focus()};search.oninput=render;
$("themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem(THEME_KEY,document.body.classList.contains("dark")?"dark":"light");themeIcon()};
editForm.onsubmit=e=>{e.preventDefault();const n=notes.find(x=>x.id===editingId);if(!n)return;n.title=editTitle.value.trim();n.content=editContent.value.trim();save();render();closeEdit()};
$("closeModal").onclick=closeEdit;modal.onclick=e=>{if(e.target===modal)closeEdit()};document.onkeydown=e=>{if(e.key==="Escape"&&modal.classList.contains("open"))closeEdit()};
load();render();
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").then(()=>console.log("SW registered")).catch(err=>console.error("SW error:",err));